services:
  n8n:
    image: n8nio/n8n:${N8N_IMAGE_TAG:-stable}
    container_name: n8n
    ports:
      - ${N8N_ACCESS_PORT:-5678}:${N8N_CONTAINER_PORT:-5678}
    environment:
      N8N_HOST: ${N8N_HOST:-localhost}
      N8N_PORT: ${N8N_CONTAINER_PORT:-5678}
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      EXECUTIONS_DATA_PRUNE: ${EXECUTIONS_DATA_PRUNE:-false}
      EXECUTIONS_DATA_MAX_AGE: ${EXECUTIONS_DATA_MAX_AGE:-30}
    volumes:
      - ${N8N_LOCAL_VOLUME_PATH:-./}:/home/node/.n8n
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --run-once # Check for updates only on startup
