services:
  n8n:
    image: n8nio/n8n:stable
    container_name: n8n
    ports:
      - 5678:5678
    volumes:
      - ../n8n_docker:/home/node/.n8n
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --run-once # Check for updates only on startup
